using AutoMapper;
using SwiftPay.Constants.Enums;
using SwiftPay.Domain.Remittance.Entities;
using SwiftPay.Domain.Notification.Entities;
using SwiftPay.DTOs.AmendmentDTO;
using SwiftPay.DTOs.CancellationDTO;
using SwiftPay.DTOs.RefundRefDTO;
using SwiftPay.DTOs.RemitReportDTO;
using SwiftPay.DTOs.RemittanceDTO;
using SwiftPay.DTOs.UserCustomerDTO;
using SwiftPay.DTOs.ComplianceDTO;
using SwiftPay.DTOs.UserRoleDTO;
using SwiftPay.Models;
using System;
using System.Text.Json.Serialization;


namespace SwiftPay.Mapper
{
    public class ConfigurationMapperProfile : Profile
    {
        public ConfigurationMapperProfile()
        {
            // ===== REMITTANCE MAPPINGS =====

            // Map CreateRemittanceDto -> RemittanceRequest
            CreateMap<CreateRemittanceDto, RemittanceRequest>()
                // RemitId is generated by the database / configuration, do not map from DTO
                .ForMember(dest => dest.RemitId, opt => opt.Ignore())
                // Audit fields controlled by server
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdateDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

            // ===== AUDIT LOG MAPPINGS =====

            // Map AuditLog -> GetAuditLogDto
            CreateMap<AuditLog, GetAuditLogDto>()
                .ForMember(dest => dest.AuditID, opt => opt.MapFrom(src => src.AuditID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.UserName, opt => opt.MapFrom(src => src.User != null ? src.User.Name : "Unknown"))
                .ForMember(dest => dest.Action, opt => opt.MapFrom(src => src.Action))
                .ForMember(dest => dest.Resource, opt => opt.MapFrom(src => src.Resource))
                .ForMember(dest => dest.Timestamp, opt => opt.MapFrom(src => src.Timestamp))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt));

            // ===== ROLE MAPPINGS =====

            // Map CreateRoleRequestDto -> Role
            CreateMap<CreateRoleRequestDto, Role>()
                // RoleId is generated by the database, do not map from DTO
                .ForMember(dest => dest.RoleId, opt => opt.Ignore())
                // Audit fields controlled by server
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore());

            // Map Role -> RoleResponseDto
            CreateMap<Role, RoleResponseDto>()
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId))
                .ForMember(dest => dest.RoleType, opt => opt.MapFrom(src => src.RoleType))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // Map CreateUserRoleRequestDto -> UserRole (for assigning roles to users)
            CreateMap<CreateUserRoleRequestDto, UserRole>()
                .ForMember(dest => dest.UserRoleId, opt => opt.Ignore())
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore())
                .ForMember(dest => dest.Role, opt => opt.Ignore());

            // Also support mapping with userId context for more flexibility
            CreateMap<(int UserId, CreateUserRoleRequestDto Dto), UserRole>()
                .ForMember(dest => dest.UserRoleId, opt => opt.Ignore())
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.Dto.RoleId))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore())
                .ForMember(dest => dest.Role, opt => opt.Ignore());

            // Map UserRole -> UserRoleResponseDto
            CreateMap<UserRole, UserRoleResponseDto>()
                .ForMember(dest => dest.UserRoleId, opt => opt.MapFrom(src => src.UserRoleId))
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId))
                .ForMember(dest => dest.RoleType, opt => opt.MapFrom(src => src.Role.RoleType))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));
            // Map RemittanceRequest -> CreateRemittanceResponseDto
            CreateMap<RemittanceRequest, CreateRemittanceResponseDto>()
                .ForMember(dest => dest.RemitId, opt => opt.MapFrom(src => src.RemitId))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status.ToString()))
                .ForMember(dest => dest.FromCurrency, opt => opt.MapFrom(src => src.FromCurrency))
                .ForMember(dest => dest.ToCurrency, opt => opt.MapFrom(src => src.ToCurrency))
                .ForMember(dest => dest.SendAmount, opt => opt.MapFrom(src => src.SendAmount))
                .ForMember(dest => dest.ReceiverAmount, opt => opt.MapFrom(src => src.ReceiverAmount))
                .ForMember(dest => dest.RateApplied, opt => opt.MapFrom(src => src.RateApplied))
                .ForMember(dest => dest.FeeApplied, opt => opt.MapFrom(src => src.FeeApplied))
                .ForMember(dest => dest.CreatedDate, opt => opt.MapFrom(src => src.CreatedDate));

            // ===== AUDIT LOG MAPPINGS =====

            // Map AuditLog -> GetAuditLogDto
            CreateMap<AuditLog, GetAuditLogDto>()
                .ForMember(dest => dest.AuditID, opt => opt.MapFrom(src => src.AuditID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.UserName, opt => opt.MapFrom(src => src.User != null ? src.User.Name : "Unknown"))
                .ForMember(dest => dest.Action, opt => opt.MapFrom(src => src.Action))
                .ForMember(dest => dest.Resource, opt => opt.MapFrom(src => src.Resource))
                .ForMember(dest => dest.Timestamp, opt => opt.MapFrom(src => src.Timestamp))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt));

            // ===== ROLE MAPPINGS =====

            // Map CreateRoleRequestDto -> Role
            CreateMap<CreateRoleRequestDto, Role>()
                // RoleId is generated by the database, do not map from DTO
                .ForMember(dest => dest.RoleId, opt => opt.Ignore())
                // Audit fields controlled by server
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore());

            // Map Role -> RoleResponseDto
            CreateMap<Role, RoleResponseDto>()
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId))
                .ForMember(dest => dest.RoleType, opt => opt.MapFrom(src => src.RoleType))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // Map CreateUserRoleRequestDto -> UserRole (for assigning roles to users)
            CreateMap<CreateUserRoleRequestDto, UserRole>()
                .ForMember(dest => dest.UserRoleId, opt => opt.Ignore())
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore())
                .ForMember(dest => dest.Role, opt => opt.Ignore());

            // Also support mapping with userId context for more flexibility
            CreateMap<(int UserId, CreateUserRoleRequestDto Dto), UserRole>()
                .ForMember(dest => dest.UserRoleId, opt => opt.Ignore())
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.Dto.RoleId))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => true))
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore())
                .ForMember(dest => dest.Role, opt => opt.Ignore());

            // Map UserRole -> UserRoleResponseDto
            CreateMap<UserRole, UserRoleResponseDto>()
                .ForMember(dest => dest.UserRoleId, opt => opt.MapFrom(src => src.UserRoleId))
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId))
                .ForMember(dest => dest.RoleType, opt => opt.MapFrom(src => src.Role.RoleType))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));
            // ===== REMIT REPORT =====
            CreateMap<CreateRemitReportDto, RemitReport>()
                .ForMember(dest => dest.ReportID, opt => opt.Ignore())
                .ForMember(dest => dest.GeneratedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

            // ===== REFUND REF =====
            CreateMap<CreateRefundRefDto, RefundRef>()
                // Primary Key generated by DB
                .ForMember(dest => dest.RefundID, opt => opt.Ignore())
                // RefundDate may be provided but let DB/service handle defaults
                .ForMember(dest => dest.RefundDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

            // ===== CANCELLATION =====
            CreateMap<CreateCancellationDto, Cancellation>()
                // Primary Key is generated by the database
                .ForMember(dest => dest.CancellationID, opt => opt.Ignore())
                // Date fields handled by server/database
                .ForMember(dest => dest.RequestedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())
                // Soft delete default
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

            // ===== USER MAPPINGS =====

            // Map CreateUserDto -> User
            CreateMap<CreateUserDto, User>()
                // UserId is generated by the database, do not map from DTO
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                // Audit fields controlled by server - set in service layer
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status uses database default - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore());

            // Map UpdateUserDto -> User (partial update)
            CreateMap<UpdateUserDto, User>()
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.Password, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore())
                // Only map Name if it's not null or empty
                .ForMember(dest => dest.Name, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Name)))
                // Only map Email if it's not null or empty
                .ForMember(dest => dest.Email, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Email)))
                // Only map Phone if it's not null or empty
                .ForMember(dest => dest.Phone, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Phone)));

            // Map User -> UserResponseDto
            CreateMap<User, UserResponseDto>()
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Phone))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt))
                .ForMember(dest => dest.Roles, opt => opt.MapFrom(src => src.UserRoles));

            // Map UserRole -> UserRoleDto
            CreateMap<UserRole, UserRoleDto>()
                .ForMember(dest => dest.UserRoleId, opt => opt.MapFrom(src => src.UserRoleId))
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId))
                .ForMember(dest => dest.RoleType, opt => opt.MapFrom(src => src.Role.RoleType))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt));

            // ===== CUSTOMER MAPPINGS =====

            // Map CreateCustomerDto -> CustomerProfile
            CreateMap<CreateCustomerDto, CustomerProfile>()
                // CustomerID is generated by the database, do not map from DTO
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                // Audit fields controlled by server - set in service layer
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status and RiskRating use database defaults - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.RiskRating, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map UpdateCustomerDto -> CustomerProfile (partial update)
            CreateMap<UpdateCustomerDto, CustomerProfile>()
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                .ForMember(dest => dest.UserID, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.RiskRating, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore())
                // Only map DOB if it's not null
                .ForMember(dest => dest.DOB, opt => opt.Condition((src, dest) => src.DOB.HasValue))
                // Only map AddressJSON if it's not null or empty
                .ForMember(dest => dest.AddressJSON, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.AddressJSON)))
                // Only map Nationality if it's not null or empty
                .ForMember(dest => dest.Nationality, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Nationality)));

            // Map CustomerProfile -> CustomerResponseDto
            CreateMap<CustomerProfile, CustomerResponseDto>()
                .ForMember(dest => dest.CustomerID, opt => opt.MapFrom(src => src.CustomerID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.DOB, opt => opt.MapFrom(src => src.DOB))
                .ForMember(dest => dest.AddressJSON, opt => opt.MapFrom(src => src.AddressJSON))
                .ForMember(dest => dest.Nationality, opt => opt.MapFrom(src => src.Nationality))
                .ForMember(dest => dest.RiskRating, opt => opt.MapFrom(src => src.RiskRating))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // ===== BENEFICIARY MAPPINGS =====

            // Map CreateBeneficiaryDto -> Beneficiary
            CreateMap<CreateBeneficiaryDto, Beneficiary>()
                // BeneficiaryID is generated by the database, do not map from DTO
                .ForMember(dest => dest.BeneficiaryID, opt => opt.Ignore())
                // Audit fields controlled by server - set in service layer
                .ForMember(dest => dest.AddedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status and VerificationStatus use database defaults - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.Customer, opt => opt.Ignore());

            // Map UpdateBeneficiaryDto -> Beneficiary (partial update)
            CreateMap<UpdateBeneficiaryDto, Beneficiary>()
                .ForMember(dest => dest.BeneficiaryID, opt => opt.Ignore())
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                .ForMember(dest => dest.AddedDate, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.Customer, opt => opt.Ignore())
                // Only map Name if it's not null or empty
                .ForMember(dest => dest.Name, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Name)))
                // Only map Country if it's not null or empty
                .ForMember(dest => dest.Country, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Country)))
                // Only map PayoutMode if it has a value
                .ForMember(dest => dest.PayoutMode, opt => opt.Condition((src, dest) => src.PayoutMode.HasValue))
                // Only map BankName if it's not null or empty
                .ForMember(dest => dest.BankName, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.BankName)))
                // Only map BankCountry if it's not null or empty
                .ForMember(dest => dest.BankCountry, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.BankCountry)))
                // Only map AccountOrWalletNo if it's not null or empty
                .ForMember(dest => dest.AccountOrWalletNo, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.AccountOrWalletNo)))
                // Only map IFSC_IBAN_SWIFT if it's not null or empty
                .ForMember(dest => dest.IFSC_IBAN_SWIFT, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.IFSC_IBAN_SWIFT)));

            // Map Beneficiary -> BeneficiaryResponseDto
            CreateMap<Beneficiary, BeneficiaryResponseDto>()
                .ForMember(dest => dest.BeneficiaryID, opt => opt.MapFrom(src => src.BeneficiaryID))
                .ForMember(dest => dest.CustomerID, opt => opt.MapFrom(src => src.CustomerID))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Country, opt => opt.MapFrom(src => src.Country))
                .ForMember(dest => dest.PayoutMode, opt => opt.MapFrom(src => src.PayoutMode))
                .ForMember(dest => dest.BankName, opt => opt.MapFrom(src => src.BankName))
                .ForMember(dest => dest.BankCountry, opt => opt.MapFrom(src => src.BankCountry))
                .ForMember(dest => dest.AccountOrWalletNo, opt => opt.MapFrom(src => src.AccountOrWalletNo))
                .ForMember(dest => dest.IFSC_IBAN_SWIFT, opt => opt.MapFrom(src => src.IFSC_IBAN_SWIFT))
                .ForMember(dest => dest.VerificationStatus, opt => opt.MapFrom(src => src.VerificationStatus))
                .ForMember(dest => dest.AddedDate, opt => opt.MapFrom(src => src.AddedDate))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // ===== AMENDMENT ===== 

            CreateMap<CreateAmendmentDto, Amendment>()
                // Primary Key is generated by the database
                .ForMember(dest => dest.AmendmentID, opt => opt.Ignore())

                // Status is usually set to 'Pending' by default in config/service

                // Date fields are handled by the server/database
                .ForMember(dest => dest.RequestedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())

                // Soft delete default
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());




            //// Optional: map back from entity to DTO for responses if needed
            //CreateMap<RemittanceRequest, CreateRemittanceDto>()
            //    .ForMember(dest => dest.CustomerId, opt => opt.MapFrom(src => src.CustomerId))
            //    .ForMember(dest => dest.BeneficiaryId, opt => opt.MapFrom(src => src.BeneficiaryId))
            //    .ForMember(dest => dest.FromCurrency, opt => opt.MapFrom(src => src.FromCurrency))
            //    .ForMember(dest => dest.ToCurrency, opt => opt.MapFrom(src => src.ToCurrency))
            //    .ForMember(dest => dest.SendAmount, opt => opt.MapFrom(src => src.SendAmount));



            //Compliance Check//
            // --- 2. ADD YOUR COMPLIANCE CHECK MAPPING HERE ---
            CreateMap<CreateComplianceCheckDto, ComplianceCheck>()
                // Ignore the Primary Key (CheckId) - DB generates this
                .ForMember(dest => dest.CheckId, opt => opt.Ignore())
                // Ignore Audit Fields - Service layer sets these
                .ForMember(dest => dest.CheckedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdateDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

            // ===== KYC RECORD MAPPINGS =====

            // Map CreateKYCRecordDto -> KYCRecord
            CreateMap<CreateKYCRecordDto, KYCRecord>()
                .ForMember(dest => dest.KYCID, opt => opt.Ignore())
                // VerificationStatus uses database default - don't set from mapper
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.VerifiedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map UpdateKYCRecordDto -> KYCRecord (partial update)
            CreateMap<UpdateKYCRecordDto, KYCRecord>()
                .ForMember(dest => dest.KYCID, opt => opt.Ignore())
                .ForMember(dest => dest.UserID, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.VerifiedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map KYCRecord -> KYCRecordResponseDto
            CreateMap<KYCRecord, KYCRecordResponseDto>()
                .ForMember(dest => dest.KYCID, opt => opt.MapFrom(src => src.KYCID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.KYCLevel, opt => opt.MapFrom(src => src.KYCLevel))
                .ForMember(dest => dest.VerificationStatus, opt => opt.MapFrom(src => src.VerificationStatus))
                .ForMember(dest => dest.VerifiedDate, opt => opt.MapFrom(src => src.VerifiedDate))
                .ForMember(dest => dest.Notes, opt => opt.MapFrom(src => src.Notes))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // ===== NOTIFICATION ALERT MAPPINGS =====
            // ===== KYC RECORD MAPPINGS =====

            // Map CreateKYCRecordDto -> KYCRecord
            CreateMap<CreateKYCRecordDto, KYCRecord>()
                .ForMember(dest => dest.KYCID, opt => opt.Ignore())
                // VerificationStatus uses database default - don't set from mapper
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.VerifiedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map UpdateKYCRecordDto -> KYCRecord (partial update)
            CreateMap<UpdateKYCRecordDto, KYCRecord>()
                .ForMember(dest => dest.KYCID, opt => opt.Ignore())
                .ForMember(dest => dest.UserID, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.VerifiedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map CreateNotificationDto -> NotificationAlert
            CreateMap<CreateNotificationDto, NotificationAlert>()
                .ForMember(dest => dest.NotificationID, opt => opt.Ignore())
                // Status uses database default - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.ReadAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());
            // Map KYCRecord -> KYCRecordResponseDto
            CreateMap<KYCRecord, KYCRecordResponseDto>()
                .ForMember(dest => dest.KYCID, opt => opt.MapFrom(src => src.KYCID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.KYCLevel, opt => opt.MapFrom(src => src.KYCLevel))
                .ForMember(dest => dest.VerificationStatus, opt => opt.MapFrom(src => src.VerificationStatus))
                .ForMember(dest => dest.VerifiedDate, opt => opt.MapFrom(src => src.VerifiedDate))
                .ForMember(dest => dest.Notes, opt => opt.MapFrom(src => src.Notes))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // Map UpdateNotificationDto -> NotificationAlert (partial update)
            CreateMap<UpdateNotificationDto, NotificationAlert>()
                .ForMember(dest => dest.NotificationID, opt => opt.Ignore())
                .ForMember(dest => dest.UserID, opt => opt.Ignore())
                .ForMember(dest => dest.RemitID, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.ReadAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());
            // ===== NOTIFICATION ALERT MAPPINGS =====

            // Map NotificationAlert -> NotificationResponseDto
            CreateMap<NotificationAlert, NotificationResponseDto>()
                .ForMember(dest => dest.NotificationID, opt => opt.MapFrom(src => src.NotificationID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.RemitID, opt => opt.MapFrom(src => src.RemitID))
                .ForMember(dest => dest.Message, opt => opt.MapFrom(src => src.Message))
                .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Category))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.ReadAt, opt => opt.MapFrom(src => src.ReadAt))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));
            // Map CreateNotificationDto -> NotificationAlert
            CreateMap<CreateNotificationDto, NotificationAlert>()
                .ForMember(dest => dest.NotificationID, opt => opt.Ignore())
                // Status uses database default - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.ReadAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // ===== UPDATE STATUS DTOs (PATCH OPERATIONS) =====
            // Map UpdateNotificationDto -> NotificationAlert (partial update)
            CreateMap<UpdateNotificationDto, NotificationAlert>()
                .ForMember(dest => dest.NotificationID, opt => opt.Ignore())
                .ForMember(dest => dest.UserID, opt => opt.Ignore())
                .ForMember(dest => dest.RemitID, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.ReadAt, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // ===== UPDATE STATUS DTOs (PATCH OPERATIONS) =====

            // UpdateCustomerRiskRatingDto and UpdateBeneficiaryVerificationStatusDto are DTO-only,
            // no entity mapping needed - values are directly assigned in service layer

            // RemitValidation -> RemitValidationDto
            CreateMap<RemitValidation, RemitValidationDto>()
                .ForMember(dest => dest.ValidationId, opt => opt.MapFrom(src => src.ValidationId))
                .ForMember(dest => dest.RemitId, opt => opt.MapFrom(src => src.RemitId))
                .ForMember(dest => dest.Rule, opt => opt.MapFrom(src => src.RuleName.ToString()))
                .ForMember(dest => dest.Result, opt => opt.MapFrom(src => src.Result.ToString()))
                .ForMember(dest => dest.Message, opt => opt.MapFrom(src => src.Message))
                .ForMember(dest => dest.CheckedDate, opt => opt.MapFrom(src => src.CheckedDate));
            // Map NotificationAlert -> NotificationResponseDto
            CreateMap<NotificationAlert, NotificationResponseDto>()
                .ForMember(dest => dest.NotificationID, opt => opt.MapFrom(src => src.NotificationID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.RemitID, opt => opt.MapFrom(src => src.RemitID))
                .ForMember(dest => dest.Message, opt => opt.MapFrom(src => src.Message))
                .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Category))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.ReadAt, opt => opt.MapFrom(src => src.ReadAt))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // Document mappings
            CreateMap<CreateDocumentDto, Document>()
                .ForMember(dest => dest.DocumentId, opt => opt.Ignore())
                .ForMember(dest => dest.UploadedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdateDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());
            // ===== UPDATE STATUS DTOs (PATCH OPERATIONS) =====

            CreateMap<Document, DocumentResponseDto>()
                .ForMember(dest => dest.DocumentId, opt => opt.MapFrom(src => src.DocumentId))
                .ForMember(dest => dest.RemitId, opt => opt.MapFrom(src => src.RemitId))
                .ForMember(dest => dest.DocType, opt => opt.MapFrom(src => src.DocType.ToString()))
                .ForMember(dest => dest.FileURI, opt => opt.MapFrom(src => src.FileURI))
                .ForMember(dest => dest.VerificationStatus, opt => opt.MapFrom(src => src.VerificationStatus.ToString()))
                .ForMember(dest => dest.UploadedDate, opt => opt.MapFrom(src => src.UploadedDate))
                .ForMember(dest => dest.CreatedDate, opt => opt.MapFrom(src => src.CreatedDate));

            // UpdateCustomerRiskRatingDto and UpdateBeneficiaryVerificationStatusDto are DTO-only,
            // no entity mapping needed - values are directly assigned in service layer
        }
    }
}