using AutoMapper;
using SwiftPay.Constants.Enums;
using SwiftPay.Domain.Remittance.Entities;
using SwiftPay.DTOs.AmendmentDTO;
using SwiftPay.DTOs.RemittanceDTO;
using SwiftPay.DTOs.UserCustomerDTO;
using SwiftPay.Models;
using System;
using SwiftPay.Domain.Remittance.Entities;
using SwiftPay.DTOs.ComplianceDTO;
using SwiftPay.DTOs.RemittanceDTO;
using System.Text.Json.Serialization;
namespace SwiftPay.Mapper
{
    public class ConfigurationMapperProfile : Profile
    {
        public ConfigurationMapperProfile()
        {
            // ===== REMITTANCE MAPPINGS =====

            // Map CreateRemittanceDto -> RemittanceRequest
            CreateMap<CreateRemittanceDto, RemittanceRequest>()
                // RemitId is generated by the database / configuration, do not map from DTO
                .ForMember(dest => dest.RemitId, opt => opt.Ignore())
                // Audit fields controlled by server
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdateDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

            // ===== USER MAPPINGS =====

            // Map CreateUserDto -> User
            CreateMap<CreateUserDto, User>()
                // UserId is generated by the database, do not map from DTO
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                // Audit fields controlled by server - set in service layer
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status uses database default - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore());

            // Map UpdateUserDto -> User (partial update)
            CreateMap<UpdateUserDto, User>()
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.Password, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore())
                // Only map Name if it's not null or empty
                .ForMember(dest => dest.Name, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Name)))
                // Only map Email if it's not null or empty
                .ForMember(dest => dest.Email, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Email)))
                // Only map Phone if it's not null or empty
                .ForMember(dest => dest.Phone, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Phone)));

            // Map User -> UserResponseDto
            CreateMap<User, UserResponseDto>()
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Phone))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt))
                .ForMember(dest => dest.Roles, opt => opt.MapFrom(src => src.UserRoles));

            // Map UserRole -> UserRoleDto
            CreateMap<UserRole, UserRoleDto>()
                .ForMember(dest => dest.UserRoleId, opt => opt.MapFrom(src => src.UserRoleId))
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId))
                .ForMember(dest => dest.RoleType, opt => opt.MapFrom(src => src.Role.RoleType))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt));

            // ===== CUSTOMER MAPPINGS =====

            // Map CreateCustomerDto -> CustomerProfile
            CreateMap<CreateCustomerDto, CustomerProfile>()
                // CustomerID is generated by the database, do not map from DTO
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                // Audit fields controlled by server - set in service layer
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status and RiskRating use database defaults - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.RiskRating, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map UpdateCustomerDto -> CustomerProfile (partial update)
            CreateMap<UpdateCustomerDto, CustomerProfile>()
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                .ForMember(dest => dest.UserID, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.RiskRating, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore())
                // Only map DOB if it's not null
                .ForMember(dest => dest.DOB, opt => opt.Condition((src, dest) => src.DOB.HasValue))
                // Only map AddressJSON if it's not null or empty
                .ForMember(dest => dest.AddressJSON, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.AddressJSON)))
                // Only map Nationality if it's not null or empty
                .ForMember(dest => dest.Nationality, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Nationality)));

            // Map CustomerProfile -> CustomerResponseDto
            CreateMap<CustomerProfile, CustomerResponseDto>()
                .ForMember(dest => dest.CustomerID, opt => opt.MapFrom(src => src.CustomerID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.DOB, opt => opt.MapFrom(src => src.DOB))
                .ForMember(dest => dest.AddressJSON, opt => opt.MapFrom(src => src.AddressJSON))
                .ForMember(dest => dest.Nationality, opt => opt.MapFrom(src => src.Nationality))
                .ForMember(dest => dest.RiskRating, opt => opt.MapFrom(src => src.RiskRating))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // ===== BENEFICIARY MAPPINGS =====

            // Map CreateBeneficiaryDto -> Beneficiary
            CreateMap<CreateBeneficiaryDto, Beneficiary>()
                // BeneficiaryID is generated by the database, do not map from DTO
                .ForMember(dest => dest.BeneficiaryID, opt => opt.Ignore())
                // Audit fields controlled by server - set in service layer
                .ForMember(dest => dest.AddedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status and VerificationStatus use database defaults - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.Customer, opt => opt.Ignore());

            // Map UpdateBeneficiaryDto -> Beneficiary (partial update)
            CreateMap<UpdateBeneficiaryDto, Beneficiary>()
                .ForMember(dest => dest.BeneficiaryID, opt => opt.Ignore())
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                .ForMember(dest => dest.AddedDate, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.Customer, opt => opt.Ignore())
                // Only map Name if it's not null or empty
                .ForMember(dest => dest.Name, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Name)))
                // Only map Country if it's not null or empty
                .ForMember(dest => dest.Country, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Country)))
                // Only map PayoutMode if it has a value
                .ForMember(dest => dest.PayoutMode, opt => opt.Condition((src, dest) => src.PayoutMode.HasValue))
                // Only map BankName if it's not null or empty
                .ForMember(dest => dest.BankName, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.BankName)))
                // Only map BankCountry if it's not null or empty
                .ForMember(dest => dest.BankCountry, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.BankCountry)))
                // Only map AccountOrWalletNo if it's not null or empty
                .ForMember(dest => dest.AccountOrWalletNo, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.AccountOrWalletNo)))
                // Only map IFSC_IBAN_SWIFT if it's not null or empty
                .ForMember(dest => dest.IFSC_IBAN_SWIFT, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.IFSC_IBAN_SWIFT)));

            // Map Beneficiary -> BeneficiaryResponseDto
            CreateMap<Beneficiary, BeneficiaryResponseDto>()
                .ForMember(dest => dest.BeneficiaryID, opt => opt.MapFrom(src => src.BeneficiaryID))
                .ForMember(dest => dest.CustomerID, opt => opt.MapFrom(src => src.CustomerID))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Country, opt => opt.MapFrom(src => src.Country))
                .ForMember(dest => dest.PayoutMode, opt => opt.MapFrom(src => src.PayoutMode))
                .ForMember(dest => dest.BankName, opt => opt.MapFrom(src => src.BankName))
                .ForMember(dest => dest.BankCountry, opt => opt.MapFrom(src => src.BankCountry))
                .ForMember(dest => dest.AccountOrWalletNo, opt => opt.MapFrom(src => src.AccountOrWalletNo))
                .ForMember(dest => dest.IFSC_IBAN_SWIFT, opt => opt.MapFrom(src => src.IFSC_IBAN_SWIFT))
                .ForMember(dest => dest.VerificationStatus, opt => opt.MapFrom(src => src.VerificationStatus))
                .ForMember(dest => dest.AddedDate, opt => opt.MapFrom(src => src.AddedDate))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            //Amendment 

            CreateMap<CreateAmendmentDto, Amendment>()
                // Primary Key is generated by the database
                .ForMember(dest => dest.AmendmentID, opt => opt.Ignore())

                // Status is usually set to 'Pending' by default in config/service

                // Date fields are handled by the server/database
                .ForMember(dest => dest.RequestedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore())

                // Soft delete default
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());




            //// Optional: map back from entity to DTO for responses if needed
            //CreateMap<RemittanceRequest, CreateRemittanceDto>()
            //    .ForMember(dest => dest.CustomerId, opt => opt.MapFrom(src => src.CustomerId))
            //    .ForMember(dest => dest.BeneficiaryId, opt => opt.MapFrom(src => src.BeneficiaryId))
            //    .ForMember(dest => dest.FromCurrency, opt => opt.MapFrom(src => src.FromCurrency))
            //    .ForMember(dest => dest.ToCurrency, opt => opt.MapFrom(src => src.ToCurrency))
            //    .ForMember(dest => dest.SendAmount, opt => opt.MapFrom(src => src.SendAmount));



            //Compliance Check//
            // --- 2. ADD YOUR COMPLIANCE CHECK MAPPING HERE ---
            CreateMap<CreateComplianceCheckDto, ComplianceCheck>()
                // Ignore the Primary Key (CheckId) - DB generates this
                .ForMember(dest => dest.CheckId, opt => opt.Ignore())
                // Ignore Audit Fields - Service layer sets these
                .ForMember(dest => dest.CheckedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdateDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

        }
    }
}