using AutoMapper;
using SwiftPay.DTOs.UserCustomerDTO;
using SwiftPay.Domain.Remittance.Entities;

namespace SwiftPay.Profiles
{
    public class CustomerBeneficiaryMapperProfile : Profile
    {
        public CustomerBeneficiaryMapperProfile()
        {
            // ===== CUSTOMER MAPPINGS =====
            
            // Map CreateCustomerDto -> CustomerProfile
            CreateMap<CreateCustomerDto, CustomerProfile>()
                // CustomerID is generated by the database, do not map from DTO
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                // Audit fields controlled by server
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status and RiskRating use database defaults - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.RiskRating, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map UpdateCustomerDto -> CustomerProfile (partial update)
            CreateMap<UpdateCustomerDto, CustomerProfile>()
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                .ForMember(dest => dest.UserID, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.RiskRating, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.User, opt => opt.Ignore());

            // Map CustomerProfile -> CustomerResponseDto
            CreateMap<CustomerProfile, CustomerResponseDto>()
                .ForMember(dest => dest.CustomerID, opt => opt.MapFrom(src => src.CustomerID))
                .ForMember(dest => dest.UserID, opt => opt.MapFrom(src => src.UserID))
                .ForMember(dest => dest.DOB, opt => opt.MapFrom(src => src.DOB))
                .ForMember(dest => dest.AddressJSON, opt => opt.MapFrom(src => src.AddressJSON))
                .ForMember(dest => dest.Nationality, opt => opt.MapFrom(src => src.Nationality))
                .ForMember(dest => dest.RiskRating, opt => opt.MapFrom(src => src.RiskRating))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));

            // ===== BENEFICIARY MAPPINGS =====
            
            // Map CreateBeneficiaryDto -> Beneficiary
            CreateMap<CreateBeneficiaryDto, Beneficiary>()
                // BeneficiaryID is generated by the database, do not map from DTO
                .ForMember(dest => dest.BeneficiaryID, opt => opt.Ignore())
                // Audit fields controlled by server
                .ForMember(dest => dest.AddedDate, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status and VerificationStatus use database defaults - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.Customer, opt => opt.Ignore());

            // Map UpdateBeneficiaryDto -> Beneficiary (partial update)
            CreateMap<UpdateBeneficiaryDto, Beneficiary>()
                .ForMember(dest => dest.BeneficiaryID, opt => opt.Ignore())
                .ForMember(dest => dest.CustomerID, opt => opt.Ignore())
                .ForMember(dest => dest.AddedDate, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.VerificationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.Customer, opt => opt.Ignore())
                // Only map Name if it's not null or empty
                .ForMember(dest => dest.Name, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Name)))
                // Only map Country if it's not null or empty
                .ForMember(dest => dest.Country, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.Country)))
                // Only map PayoutMode if it has a value
                .ForMember(dest => dest.PayoutMode, opt => opt.Condition((src, dest) => src.PayoutMode.HasValue))
                // Only map BankName if it's not null or empty
                .ForMember(dest => dest.BankName, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.BankName)))
                // Only map BankCountry if it's not null or empty
                .ForMember(dest => dest.BankCountry, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.BankCountry)))
                // Only map AccountOrWalletNo if it's not null or empty
                .ForMember(dest => dest.AccountOrWalletNo, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.AccountOrWalletNo)))
                // Only map IFSC_IBAN_SWIFT if it's not null or empty
                .ForMember(dest => dest.IFSC_IBAN_SWIFT, opt => opt.Condition((src, dest) => !string.IsNullOrEmpty(src.IFSC_IBAN_SWIFT)));

            // Map Beneficiary -> BeneficiaryResponseDto
            CreateMap<Beneficiary, BeneficiaryResponseDto>()
                .ForMember(dest => dest.BeneficiaryID, opt => opt.MapFrom(src => src.BeneficiaryID))
                .ForMember(dest => dest.CustomerID, opt => opt.MapFrom(src => src.CustomerID))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Country, opt => opt.MapFrom(src => src.Country))
                .ForMember(dest => dest.PayoutMode, opt => opt.MapFrom(src => src.PayoutMode))
                .ForMember(dest => dest.BankName, opt => opt.MapFrom(src => src.BankName))
                .ForMember(dest => dest.BankCountry, opt => opt.MapFrom(src => src.BankCountry))
                .ForMember(dest => dest.AccountOrWalletNo, opt => opt.MapFrom(src => src.AccountOrWalletNo))
                .ForMember(dest => dest.IFSC_IBAN_SWIFT, opt => opt.MapFrom(src => src.IFSC_IBAN_SWIFT))
                .ForMember(dest => dest.VerificationStatus, opt => opt.MapFrom(src => src.VerificationStatus))
                .ForMember(dest => dest.AddedDate, opt => opt.MapFrom(src => src.AddedDate))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt));
        }
    }
}
