using AutoMapper;
using SwiftPay.DTOs.UserCustomerDTO;
using SwiftPay.Models;

namespace SwiftPay.Profiles
{
    public class UserMapperProfile : Profile
    {
        public UserMapperProfile()
        {
            // Map CreateUserDto -> User
            CreateMap<CreateUserDto, User>()
                // UserId is generated by the database, do not map from DTO
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                // Audit fields controlled by server - set in service layer
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                // Status uses database default - don't set from mapper
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore());

            // Map UpdateUserDto -> User (partial update)
            CreateMap<UpdateUserDto, User>()
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.Password, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore())
                .ForMember(dest => dest.UserRoles, opt => opt.Ignore());

            // Map User -> UserResponseDto
            CreateMap<User, UserResponseDto>()
                .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
                .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Phone))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt))
                .ForMember(dest => dest.Roles, opt => opt.MapFrom(src => src.UserRoles));

            // Map UserRole -> UserRoleDto
            CreateMap<UserRole, UserRoleDto>()
                .ForMember(dest => dest.UserRoleId, opt => opt.MapFrom(src => src.UserRoleId))
                .ForMember(dest => dest.RoleId, opt => opt.MapFrom(src => src.RoleId))
                .ForMember(dest => dest.RoleType, opt => opt.MapFrom(src => src.Role.RoleType))
                .ForMember(dest => dest.IsActive, opt => opt.MapFrom(src => src.IsActive))
                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt));
        }
    }
}
